name: Release on tag

on:
  push:
    tags:
      - 'v*'            # cuando hagas push de un tag que empiece con v (v1.0.0, v1.1.0, etc.)

permissions:
  contents: write        # necesario para crear el Release

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build JAR
        run: mvn -B -DskipTests=false clean package

      - name: Create GitHub Release (con JAR)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "HolaMundoApp ${{ github.ref_name }}"
          body: "Release generado automáticamente desde GitHub Actions."
          files: |
            target/*.jar
          draft: false
          prerelease: false
